version: '3.8'
services:
  frontend:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - '5173:5173'
  server:
    build:
      context: server
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - '3001:3001'
