name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Check coverage threshold
        run: npm run test:coverage

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test
    services:
      web:
        image: node:18
        options: >-
          --health-cmd \"curl --fail http://localhost:5173 || exit 1\" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5173:5173
        volumes:
          - ./:/app
        working-directory: /app
        command: bash -lc \"npm ci && npm run dev\"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Wait for dev server
        run: npx wait-on http://localhost:5173
      - name: Run Cypress
        run: npm run cy:run

